### ISSUE TITLE
ct-lessen & ct-greaten

### ISSUE THREAD

**Issue by zzkt** [neeasade/ct.el#12]
Looks like the functions `ct-lessen` and `ct-greaten` were removed at e9ca52a2f58cf4155da77069e3f32736b91ec59e is this an oversight? or is there another way to lessen or greaten colour values?

**Comment by neeasade** [comment]
Apologies, just saw this issue

Hi! I removed this because I realized I had not uses of it, and couldn't find any online. I'll put them back

**Comment by neeasade** [comment]
one reason for removing them initially is they operate on a percent of change, when typically you might want to use something like `ct-edit-lab-l-inc` in the context of `ct-iterate` (until a contrast or distance condition)

**Comment by zzkt** [comment]
Thanks @neeasade. I'm using them to make adjustments from a base value in an existing theme. works well enough in this situation, especially since it checks for `ct-light-p`
